#!/bin/bash
echo "================================================"
echo "     CSL v1.3.0 Release - READY TO PUBLISH!"
echo "================================================"
echo ""
echo "The v1.3.0 tag has been pushed to GitHub."
echo ""
echo "To create the release on GitHub:"
echo ""
echo "1. Go to: https://github.com/ricfulop/CSL/releases/new"
echo ""
echo "2. Select tag: v1.3.0"
echo ""
echo "3. Release title: CSL v1.3.0 - Triple Lindy Real-time Control System"
echo ""
echo "4. Copy the release notes from: RELEASE_NOTES_v1.3.0.md"
echo ""
echo "5. Check 'Set as the latest release'"
echo ""
echo "6. Click 'Publish release'"
echo ""
echo "================================================"
echo "Alternatively, if you have GitHub CLI installed:"
echo "gh release create v1.3.0 --title 'CSL v1.3.0 - Triple Lindy Real-time Control System' --notes-file RELEASE_NOTES_v1.3.0.md"
