name: Golden Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (none required)
        run: echo "No external deps"
      - name: Run conformance and golden check
        run: |
          make golden-check
      - name: APS auth check (optional)
        env:
          APS_CLIENT_ID: ${{ secrets.APS_CLIENT_ID }}
          APS_CLIENT_SECRET: ${{ secrets.APS_CLIENT_SECRET }}
          APS_SCOPES: data:read data:write
        run: |
          make aps-auth

